version: '3.9'

services:
  # üé¨ Booking database
  booking-db:
    image: postgres:16
    container_name: booking-db
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_pass
      TZ: Asia/Kolkata
      PGTZ: Asia/Kolkata
    ports:
      - "5433:5432"
    networks:
      - movie-net
    volumes:
      - booking_data:/var/lib/postgresql/data

  # üçø Movie database
  movie-db:
    image: postgres:16
    container_name: movie-db
    environment:
      POSTGRES_DB: movie_db
      POSTGRES_USER: movie_user
      POSTGRES_PASSWORD: movie_pass
      TZ: Asia/Kolkata
      PGTZ: Asia/Kolkata
    ports:
      - "5434:5432"
    networks:
      - movie-net
    volumes:
      - movie_data:/var/lib/postgresql/data

  # üë§ User database
  user-db:
    image: postgres:16
    container_name: user-db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: user_pass
      TZ: Asia/Kolkata
      PGTZ: Asia/Kolkata
    ports:
      - "5435:5432"
    networks:
      - movie-net
    volumes:
      - user_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - movie-net
    command: ["redis-server", "--save", "", "--appendonly", "no"]

  # üì® RabbitMQ for async notifications
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"      # RabbitMQ broker
      - "15672:15672"    # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - movie-net

networks:
  movie-net:
    driver: bridge

volumes:
  booking_data:
  movie_data:
  user_data:
