# server:
#   port: 8086

# spring:
#   application:
#     name: movie-service

  datasource:
    url: jdbc:postgresql://localhost:5434/movie_db
    username: movie_user
    password: movie_pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

# springdoc:
#   swagger-ui:
#     path: /swagger-ui.html
#     operationsSorter: method
#     tagsSorter: alpha

# management:
#   endpoints:
#     web:
#       exposure:
#         include: health,info
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/
#   instance:
#     prefer-ip-address: true
